from tkinter import *
x=Tk()
x.minsize(300,600)
x.maxsize(600,1200)
topframe=Frame(x)
topframe.pack(side=TOP)
b1=Button(topframe,text='button1',activebackground='pink')
b1.grid(row=0,column=1)
b2=Button(topframe,text='button2',activebackground='grey')
b2.grid(row=0,column=2)
l1=Label(topframe,text='Label',bg='yellow')
l1.grid(row=2,column=1)
e1=Entry(topframe, bd=2)
e1.grid(row=2,column=2)
lframe=Frame(x)
lframe.pack(side=LEFT)
b1=Button(lframe,text='button1',activebackground='pink')
b1.grid(row=0,column=1)
b2=Button(lframe,text='button2',activebackground='grey')
b2.grid(row=0,column=2)

rframe=Frame(x)
rframe.pack(side=RIGHT)
l1=Label(rframe,text='Label',bg='yellow')
l1.pack(side=LEFT)
l2=Label(rframe,text='Label',bg='yellow')
l2.pack(side=RIGHT)

x.mainloop()
