from tkinter import *
x=Tk()
x.minsize(200,200)
l=Label(x,text='Button Operation')
l1=Label(x,text='Name')
e1=Entry(x)
b=Button(x,text='button1',bg='pink',fg='orange',activeforeground='white',activebackground='black',bd=8,relief=RIDGE)
b1=Button(x,text='button2',bg='pink',fg='orange',activeforeground='white',activebackground='black',bd=8)
b2=Button(x,text='button3',bd=8,justify=RIGHT,relief=GROOVE,state=ACTIVE,underline=5,wraplength=1)
l.grid(row=0,columnspan=3)
l1.grid(row=2,column=1,pady=5)
e1.grid(row=2,column=2,pady=5)
b.grid(row=4,columnspan=3,sticky=W)
b1.grid(row=4,columnspan=3,sticky=E)
b2.grid(row=6,columnspan=3,sticky=N)
x.mainloop()